/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { StaticDataDTO } from '../model';
/**
 * BlizzardDataApi - axios parameter creator
 * @export
 */
export const BlizzardDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Fetch static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchStaticData: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/blizzardData/fetchStaticData`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuthSample required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuthSample", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStaticData: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/blizzardData/getStaticData`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuthSample required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuthSample", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlizzardDataApi - functional programming interface
 * @export
 */
export const BlizzardDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BlizzardDataApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Fetch static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchStaticData(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchStaticData(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStaticData(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StaticDataDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStaticData(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BlizzardDataApi - factory interface
 * @export
 */
export const BlizzardDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BlizzardDataApiFp(configuration)
    return {
        /**
         * 
         * @summary Fetch static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchStaticData(options?: any): AxiosPromise<void> {
            return localVarFp.fetchStaticData(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get static data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStaticData(options?: any): AxiosPromise<StaticDataDTO> {
            return localVarFp.getStaticData(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlizzardDataApi - interface
 * @export
 * @interface BlizzardDataApi
 */
export interface BlizzardDataApiInterface {
    /**
     * 
     * @summary Fetch static data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlizzardDataApiInterface
     */
    fetchStaticData(options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get static data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlizzardDataApiInterface
     */
    getStaticData(options?: AxiosRequestConfig): AxiosPromise<StaticDataDTO>;

}

/**
 * BlizzardDataApi - object-oriented interface
 * @export
 * @class BlizzardDataApi
 * @extends {BaseAPI}
 */
export class BlizzardDataApi extends BaseAPI implements BlizzardDataApiInterface {
    /**
     * 
     * @summary Fetch static data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlizzardDataApi
     */
    public fetchStaticData(options?: AxiosRequestConfig) {
        return BlizzardDataApiFp(this.configuration).fetchStaticData(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get static data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlizzardDataApi
     */
    public getStaticData(options?: AxiosRequestConfig) {
        return BlizzardDataApiFp(this.configuration).getStaticData(options).then((request) => request(this.axios, this.basePath));
    }
}
