/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CharacterDTO } from './character-dto';

/**
 * 
 * @export
 * @interface CharacterArrayDTO
 */
export interface CharacterArrayDTO {
    /**
     * 
     * @type {Array<CharacterDTO>}
     * @memberof CharacterArrayDTO
     */
    'characterDTOs'?: Array<CharacterDTO>;
}

