/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CovenantDTO } from './covenant-dto';

/**
 * Covenant progress DTO
 * @export
 * @interface CovenantProgressDTO
 */
export interface CovenantProgressDTO {
    /**
     * 
     * @type {CovenantDTO}
     * @memberof CovenantProgressDTO
     */
    'covenantDTO'?: CovenantDTO;
    /**
     * 
     * @type {number}
     * @memberof CovenantProgressDTO
     */
    'renown_level': number;
}

