/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FactionDTO } from './faction-dto';
import { RealmDTO } from './realm-dto';

/**
 * Guild index DTO
 * @export
 * @interface GuildIndexDTO
 */
export interface GuildIndexDTO {
    /**
     * 
     * @type {number}
     * @memberof GuildIndexDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GuildIndexDTO
     */
    'name': string;
    /**
     * 
     * @type {RealmDTO}
     * @memberof GuildIndexDTO
     */
    'realmDTO': RealmDTO;
    /**
     * 
     * @type {FactionDTO}
     * @memberof GuildIndexDTO
     */
    'factionDTO': FactionDTO;
    /**
     * 
     * @type {boolean}
     * @memberof GuildIndexDTO
     */
    'useApplication': boolean;
}

