/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LocalizedDTO
 */
export interface LocalizedDTO {
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'enUS': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'esMX': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'ptBR': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'deDE': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'enGB': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'esES': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'frFR': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'itIT': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'ruRU': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'koKR': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'zhTW': string;
    /**
     * 
     * @type {string}
     * @memberof LocalizedDTO
     */
    'zhCN': string;
}

