/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LocalizedDTO } from './localized-dto';
import { SpecializationRoleDTO } from './specialization-role-dto';

/**
 * 
 * @export
 * @interface PlayableSpecializationDTO
 */
export interface PlayableSpecializationDTO {
    /**
     * 
     * @type {number}
     * @memberof PlayableSpecializationDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PlayableSpecializationDTO
     */
    'mediaURL': string;
    /**
     * 
     * @type {number}
     * @memberof PlayableSpecializationDTO
     */
    'playableClassId': number;
    /**
     * 
     * @type {LocalizedDTO}
     * @memberof PlayableSpecializationDTO
     */
    'localizedDTO': LocalizedDTO;
    /**
     * 
     * @type {SpecializationRoleDTO}
     * @memberof PlayableSpecializationDTO
     */
    'specializationRoleDTO': SpecializationRoleDTO;
}

