/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LocalizedDTO } from './localized-dto';
import { PlayableSpecializationDTO } from './playable-specialization-dto';

/**
 * 
 * @export
 * @interface PlayableClassDTO
 */
export interface PlayableClassDTO {
    /**
     * 
     * @type {number}
     * @memberof PlayableClassDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PlayableClassDTO
     */
    'mediaURL': string;
    /**
     * 
     * @type {LocalizedDTO}
     * @memberof PlayableClassDTO
     */
    'localizedDTO': LocalizedDTO;
    /**
     * 
     * @type {Array<PlayableSpecializationDTO>}
     * @memberof PlayableClassDTO
     */
    'playableSpecializationDTOs': Array<PlayableSpecializationDTO>;
}

