/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RealmRegionDTO
 */
export interface RealmRegionDTO {
    /**
     * 
     * @type {number}
     * @memberof RealmRegionDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RealmRegionDTO
     */
    'localizedData': string;
}

