/* tslint:disable */
/* eslint-disable */
/**
 * Swagger WoW Comanion
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CovenantDTO } from './covenant-dto';
import { FactionDTO } from './faction-dto';
import { PlayableClassDTO } from './playable-class-dto';
import { PlayableRaceDTO } from './playable-race-dto';
import { PlayableSpecializationDTO } from './playable-specialization-dto';
import { RealmDTO } from './realm-dto';
import { SpecializationRoleDTO } from './specialization-role-dto';

/**
 * 
 * @export
 * @interface StaticDataDTO
 */
export interface StaticDataDTO {
    /**
     * 
     * @type {Array<CovenantDTO>}
     * @memberof StaticDataDTO
     */
    'covenantDTOs': Array<CovenantDTO>;
    /**
     * 
     * @type {Array<PlayableRaceDTO>}
     * @memberof StaticDataDTO
     */
    'playableRaceDTOs': Array<PlayableRaceDTO>;
    /**
     * 
     * @type {Array<FactionDTO>}
     * @memberof StaticDataDTO
     */
    'factionDTOs': Array<FactionDTO>;
    /**
     * 
     * @type {Array<PlayableClassDTO>}
     * @memberof StaticDataDTO
     */
    'playableClassDTOs': Array<PlayableClassDTO>;
    /**
     * 
     * @type {Array<PlayableSpecializationDTO>}
     * @memberof StaticDataDTO
     */
    'playableSpecializationDTOs': Array<PlayableSpecializationDTO>;
    /**
     * 
     * @type {Array<SpecializationRoleDTO>}
     * @memberof StaticDataDTO
     */
    'specializationRoleDTOs': Array<SpecializationRoleDTO>;
    /**
     * 
     * @type {Array<RealmDTO>}
     * @memberof StaticDataDTO
     */
    'realmDTOs': Array<RealmDTO>;
}

